[package]
name = "asm"
version = "0.1.0"
edition = "2021"

[features]
huge_files = ["bytes/huge_files"]

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
vm = { path = "../vm" }
bytes = { path = "../bytes" }