[package]
name = "lex"
version = "0.1.0"
edition = "2021"

[features]
huge_files = []

[dependencies]
bytes = { path = "../bytes" }
phf = { version = "0.11.2", features = ["macros"] }
error = { path = "../error" }
warning = { path = "../warning" }