use std::fmt::Debug;
use phf::phf_map;

#[derive(Debug)]
pub struct WithSpan<T> where T: Debug {
    pub value: T,
    pub start: usize,
    pub end: usize,
}

#[derive(Debug)]
pub enum Token {
    Char(char),
    Identifier(String),
    Number(f64),
    DocComment(String),
    LineComment(String),
    Symbol(Symbol),
    Keyword(Keyword),
    String(String),
    EndOfInput,
    MarkupStartTag(String),
    MarkupKey(String),
    MarkupStartTagEnd,
    MarkupClose,
    MarkupText(String),
    MarkupEndTag(String),
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub enum Keyword {
    As,
    Await,
    Async,
    Break,
    Class,
    Continue,
    Else,
    Enum,
    Fn,
    For,
    If,
    In,
    Let,
    Mut,
    Match,
    Nil,
    Return,
    This,
    ThisCase,
    Type,
    While,
    Use,
}

pub static KEYWORDS: phf::Map<&'static str, Keyword> = phf_map! {
    "as" => Keyword::As,
    "await" => Keyword::Await,
    "async" => Keyword::Async,
    "break" => Keyword::Break,
    "class" => Keyword::Class,
    "continue" => Keyword::Continue,
    "else" => Keyword::Else,
    "enum" => Keyword::Enum,
    "fn" => Keyword::Fn,
    "for" => Keyword::For,
    "if" => Keyword::If,
    "in" => Keyword::In,
    "let" => Keyword::Let,
    "mut" => Keyword::Mut,
    "match" => Keyword::Match,
    "nil" => Keyword::Nil,
    "return" => Keyword::Return,
    "this" => Keyword::This,
    "This" => Keyword::ThisCase,
    "type" => Keyword::Type,
    "while" => Keyword::While,
    "use" => Keyword::Use,
};

#[derive(Copy, Clone, Debug)]
pub enum Symbol {
    Equals,
    EqualsEquals,
    EqualsRightAngle,
    ExclamationMark,
    ExclamationMarkEquals,
    LeftAngle,
    LeftAngleEquals,
    LeftAngleLeftAngle,
    LeftAngleLeftAngleEquals,
    RightAngle,
    RightAngleEquals,
    RightAngleRightAngle,
    RightAngleRightAngleEquals,
    Plus,
    PlusEquals,
    Minus,
    MinusEquals,
    Star,
    StarEquals,
    Percent,
    PercentEquals,
    Slash,
    SlashEquals,
    StarStar,
    StarStarEquals,
    Pipe,
    PipeEquals,
    Ampersand,
    AmpersandEquals,
    Caret,
    CaretEquals,
    PipePipe,
    PipePipeEquals,
    AmpersandAmpersand,
    AmpersandAmpersandEquals,
    Dot,
    QuestionMark,
    QuestionMarkDot,
    Comma,
    Colon,
    Semicolon,
    LeftParenthesis,
    RightParenthesis,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
}